# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 00:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20160613_2357'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyTodo',
            new_name='todo',
        ),
    ]
